#!/bin/sh
# elvis: linkedin	-- Search LinkedIn
# Author: elton santana

. surfraw || exit 1

w3_config_hook () {
    def SURFRAW_linkedin_filter all
}

w3_usage_hook () {
    cat <<EOF

Usage: $w3_argv0 [options] [search-string]
Description:
 Search LinkedIn (https://linkedin.com)

Local options:
 -sort=CATEGORIES
 -s=CATEGORIES
          new           |   Most recently asked (default)
          feat          |   Questions with open bounties
          vote          |   Questions with most votes
          active        |   Recently active
          null          |   No upvoted answers
          faq           |   Questions with the most links
                            Default: new

 -u                     |   Search Unix & Linux Exchange
                            Default: no

 -num=NUMBER            |   Number of results per page
                            Default: $SURFRAW_stack_results

EOF
    w3_global_usage
}
#mkopts companies people groups schools

w3_complete_hook_opt ()
{
    local opt="$1"
    case "$opt" in
        -filter=*) echo all companies people groups schools ;;
        *) return 1 ;;
    esac
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -f*=*)      setopt   SURFRAW_linkedin_filter "$optarg" ;;
    -a*)        setopt   SURFRAW_linkedin_filter all       ;;
    -c*)        setopt   SURFRAW_linkedin_filter companies ;;
    -p*)        setopt   SURFRAW_linkedin_filter people    ;;
    -g*)        setopt   SURFRAW_linkedin_filter groups    ;;
    -s|-news)   setopt   SURFRAW_linkedin_filter schools   ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"

url="https://www.linkedin.com"

# No arguments passed
if [ -z "$w3_args" ]; then
    w3_browse_url "$url"
else
    escaped_args=$(w3_url_of_arg $w3_args)
    w3_browse_url "${url}/search/results/${SURFRAW_linkedin_filter}/?keywords=${escaped_args}"
fi
