# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' max-errors 1 numeric
zstyle :compinstall filename "$HOME/.zshrc"

# Use modern completion system
autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.config/histfile
HISTSIZE=100000
SAVEHIST=100000
setopt beep
# End of lines configured by zsh-newuser-install

# disable XON/XOFF used to pause terminal output (CTRL+S) and resume (CTRL+Q)
stty -ixon

# Bindkeys - view: man zshzle
set -o vi # set zsh to use vi-style line editing
bindkey -v # set 'viins' keymap - view keybinds: bindkey -M viins
#bindkey -e # set 'emacs' keymap - view keybinds: bindkey -M emacs

# custom keybinds
bindkey -M viins 'jj' vi-cmd-mode
#bindkey -M viins "^@" set-mark-command
bindkey -M viins "^A" beginning-of-line
bindkey -M viins "^E" end-of-line
#bindkey -M viins "^B" backward-char
#bindkey -M viins "^F" forward-char
bindkey -M viins "^G" send-break
#bindkey -M viins "^M" accept-line
bindkey -M viins "^P" up-line-or-history
bindkey -M viins "^N" down-line-or-history
bindkey -M viins "^O" accept-line-and-down-history
bindkey -M viins "^Q" push-line
#bindkey -M viins "^S" history-incremental-search-forward
bindkey -M viins "^K" kill-line
bindkey -M viins "^W" backward-kill-word

# enable edit command line in vim (CTRL+X, CTRL+E)
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M viins "^X^E" edit-command-line

# alias
[ -f ~/.config/shell_aliases ] && source ~/.config/shell_aliases

# bitwarden
#export SSH_AUTH_SOCK="$HOME"/.bitwarden-ssh-agent.sock
export SSH_AUTH_SOCK="$HOME"/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock

# hyprland
# UWSM - Universal Wayland Session Manager
if uwsm check may-start && uwsm select; then
  exec uwsm start default
fi

# neovim
export EDITOR='nvim'
#export PATH="$PATH:/opt/nvim-linux-x86_64/bin"

# secrets
if [ -f "$HOME/.config/private/private.sh" ]; then
  source "$HOME/.config/private/private.sh"
else
  echo "missing secrets file at: $HOME/.config/private/private.sh" >&2
fi

# wezterm
source "$HOME"/.config/wezterm/assets/shell-integration/wezterm.sh
# generated by: wezterm shell-completion --shell zsh
source "$HOME"/.config/zsh/wezterm.zsh

# zsh
source "$HOME/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$HOME/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# fzf
source <(fzf --zsh)

# zoxide
eval "$(zoxide init zsh)"

# ripgrep
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME"/ripgrep/ripgreprc

# starship 
eval "$(starship init zsh)"
