# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' max-errors 1 numeric
zstyle :compinstall filename "$HOME/.zshrc"

# Use modern completion system
autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.config/histfile
HISTSIZE=100000
SAVEHIST=100000
setopt beep
# End of lines configured by zsh-newuser-install

# disable XON/XOFF used to pause terminal output (CTRL+S) and resume (CTRL+Q)
stty -ixon

# alias
[ -f "$HOME/.config/shell_common" ] && source "$HOME/.config/shell_common"

# zsh vi-mode
[ -f "$HOME/.config/zsh/vi-mode.zsh" ] && source "$HOME/.config/zsh/vi-mode.zsh"

# hyprland
# UWSM - Universal Wayland Session Manager
if uwsm check may-start && uwsm select; then
  exec uwsm start default
fi

# secrets
if [ -f "$HOME/.config/private/private.sh" ]; then
  source "$HOME/.config/private/private.sh"
else
  echo "missing secrets file at: $HOME/.config/private/private.sh" >&2
fi

# wezterm
source "$HOME"/.config/wezterm/assets/shell-integration/wezterm.sh
# generated by: wezterm shell-completion --shell zsh
source "$HOME"/.config/zsh/wezterm.zsh

# zsh
source "$HOME/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$HOME/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# fzf
source <(fzf --zsh)

# zoxide
eval "$(zoxide init zsh)"

# starship 
eval "$(starship init zsh)"

# start tmux
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]]; then
  if [ -z "$TMUX" ] && tmux ls -F "#{session_name}" | grep -Fqx "default"; then
    # creates a new session if a new terminal window is created
    tmux new-session
  else
    # creates or attaches to the default session
    tmux attach-session -t default || tmux new-session -s default
  fi
fi
